# Generated by Django 6.0.6 on 2026-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('hear_about', models.CharField(blank=True, choices=[('Google Search', 'Google Search'), ('Social Media', 'Social Media'), ('Referral', 'Referral'), ('Advertisement', 'Advertisement'), ('Other', 'Other')], max_length=30)),
                ('message', models.TextField()),
                ('interests', models.JSONField(blank=True, default=list)),
                ('budget', models.CharField(blank=True, choices=[('Under $2,000', 'Under $2,000'), ('$2,000 – $5,000', '$2,000 – $5,000'), ('$5,000 – $10,000', '$5,000 – $10,000'), ('$10,000+', '$10,000+'), ("Let's Discuss", "Let's Discuss")], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
